# -*- coding: utf-8 -*-
"""Regression Project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17_eWhFEyadpFJs8OQ5l5dhEXWYatiaKZ
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.linear_model import Lasso
from sklearn import metrics
from sklearn.preprocessing import OrdinalEncoder
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import MinMaxScaler

# loading the data from csv file to pandas dataframe
car_dataset = pd.read_csv('D:\PYTHON\ML\REGRESSION\cardata.csv')

car_dataset.head()

car_dataset.shape

car_dataset.info()

car_dataset.isnull().sum()

print(car_dataset.Year.value_counts())
print(car_dataset.Fuel_Type.value_counts())
print(car_dataset.Seller_Type.value_counts())
print(car_dataset.Transmission.value_counts())

car_dataset.sample(4
                   )

x_train, x_test, y_train, y_test = train_test_split(car_dataset.drop(['Car_Name', 'Selling_Price'],
                                                                     axis=1), car_dataset['Selling_Price'],
                                                                     test_size=0.2, random_state=2)

categorical_cols = ['Fuel_Type', 'Seller_Type', 'Transmission']
transformer = ColumnTransformer(
    transformers=[
        ('tnf1', OrdinalEncoder(categories=[['Petrol','Diesel','CNG'],
                                            ['Dealer','Individual'],
                                            ['Manual','Automatic']]), categorical_cols),
        ('tnf2', MinMaxScaler(), ['Year', 'Present_Price', 'Kms_Driven'])
    ],
    remainder='passthrough'
)

transformer.fit(x_train)
x_train = transformer.transform(x_train)
x_test = transformer.transform(x_test)

x_train.shape

lr = LinearRegression()

lr.fit(x_train, y_train)

training_data_prediction = lr.predict(x_train)

eror_score=  metrics.r2_score(y_train, training_data_prediction)
print("R squared Error : ", eror_score)

plt.figure()
plt.scatter(y_train, training_data_prediction, color='steelblue', alpha=0.7)
plt.xlabel("Actual Price")
plt.ylabel("Predicted Price")
plt.title("Linear Regression – Training Data")


test_data_prediction = lr.predict(x_test)

error_score = metrics.r2_score(y_test, test_data_prediction)
print("R squared Error : ", error_score)

plt.figure()
plt.scatter(y_test, test_data_prediction, color='darkorange', alpha=0.7)
plt.xlabel("Actual Price")
plt.ylabel("Predicted Price")
plt.title("Linear Regression – Test Data")


ls  = Lasso(alpha=0.01)

ls.fit(x_train, y_train)

training_data_prediction = ls.predict(x_train)

error_score = metrics.r2_score(y_train, training_data_prediction)
print("R squared Error:", error_score)

plt.figure()
plt.scatter(y_train, training_data_prediction, color='seagreen', alpha=0.7)
plt.xlabel("Actual Price")
plt.ylabel("Predicted Price")
plt.title("Lasso Regression – Training Data")


ls.fit(x_test, y_test)
test_data_prediction = ls.predict(x_test)

test_data_prediction= ls.predict(x_test)

error_score = metrics.r2_score(y_test, test_data_prediction)
print("R squared Error:", error_score)

plt.figure()
plt.scatter(y_test, test_data_prediction, color='crimson', alpha=0.7)
plt.xlabel("Actual Price")
plt.ylabel("Predicted Price")
plt.title("Lasso Regression – Test Data")



import seaborn as sns

# Linear Regression test predictions
lr_test_prediction = lr.predict(x_test)

# Lasso Regression test predictions
# In the current notebook state, 'test_data_prediction' holds the Lasso predictions on x_test.
lasso_test_prediction = test_data_prediction

# Calculate residuals (errors)
lr_residuals = y_test - lr_test_prediction
lasso_residuals = y_test - lasso_test_prediction

plt.figure(figsize=(14, 6))

# Plot histogram for Linear Regression residuals
plt.subplot(1, 2, 1) # 1 row, 2 columns, 1st plot
sns.histplot(lr_residuals, kde=True, color='blue', bins=30)
plt.title('Distribution of Linear Regression Errors (Test Data)')
plt.xlabel('Residuals (Actual Price - Predicted Price)')
plt.ylabel('Frequency')

# Plot histogram for Lasso Regression residuals
plt.subplot(1, 2, 2) # 1 row, 2 columns, 2nd plot
sns.histplot(lasso_residuals, kde=True, color='red', bins=30)
plt.title('Distribution of Lasso Regression Errors (Test Data)')
plt.xlabel('Residuals (Actual Price - Predicted Price)')
plt.ylabel('Frequency')

plt.tight_layout()

import tkinter as tk
from tkinter import ttk, messagebox
import pandas as pd

# ── Show all matplotlib figures that were built earlier ──────────────────────
plt.show()

# ── Tkinter UI ───────────────────────────────────────────────────────────────
def launch_ui():
    root = tk.Tk()
    root.title("🚗  Car Selling Price Predictor")
    root.resizable(False, False)

    # ── Colour palette ────────────────────────────────────────────────────────
    BG       = "#1e1e2e"
    CARD     = "#2a2a3e"
    ACCENT   = "#7c6af7"
    FG       = "#cdd6f4"
    FG_DIM   = "#a6adc8"
    ENTRY_BG = "#313244"
    BTN_FG   = "#ffffff"

    root.configure(bg=BG)

    style = ttk.Style()
    style.theme_use("clam")
    style.configure("TLabel",      background=CARD, foreground=FG,     font=("Segoe UI", 10))
    style.configure("Title.TLabel",background=BG,   foreground=ACCENT, font=("Segoe UI", 15, "bold"))
    style.configure("Sub.TLabel",  background=BG,   foreground=FG_DIM, font=("Segoe UI", 9))
    style.configure("Card.TFrame", background=CARD)
    style.configure("TCombobox",   fieldbackground=ENTRY_BG, foreground=FG, background=CARD,
                    selectbackground=ENTRY_BG, selectforeground=FG, font=("Segoe UI", 10))
    style.map("TCombobox", fieldbackground=[("readonly", ENTRY_BG)])

    # ── Header ────────────────────────────────────────────────────────────────
    header = tk.Frame(root, bg=BG, pady=16)
    header.pack(fill="x", padx=24)
    ttk.Label(header, text="Car Selling Price Predictor", style="Title.TLabel").pack()
    ttk.Label(header, text="Linear Regression  •  Enter details below",
              style="Sub.TLabel").pack(pady=(2, 0))

    # ── Card frame ────────────────────────────────────────────────────────────
    card = ttk.Frame(root, style="Card.TFrame", padding=20)
    card.pack(padx=24, pady=(0, 16), fill="both")

    def make_label(row, text):
        lbl = ttk.Label(card, text=text)
        lbl.grid(row=row, column=0, sticky="w", padx=(4, 16), pady=6)

    def entry_widget(row, default):
        var = tk.StringVar(value=str(default))
        e = tk.Entry(card, textvariable=var, bg=ENTRY_BG, fg=FG, insertbackground=FG,
                     relief="flat", font=("Segoe UI", 10), width=22,
                     highlightthickness=1, highlightbackground=ACCENT,
                     highlightcolor=ACCENT)
        e.grid(row=row, column=1, sticky="ew", padx=4, pady=6)
        return var

    def combo_widget(row, options, default):
        var = tk.StringVar(value=default)
        cb = ttk.Combobox(card, textvariable=var, values=options,
                          state="readonly", width=20, font=("Segoe UI", 10))
        cb.grid(row=row, column=1, sticky="ew", padx=4, pady=6)
        return var

    card.columnconfigure(1, weight=1)

    fields = [
        ("Year (2003 – 2023):",    lambda r: entry_widget(r, 2015)),
        ("Present Price (Lakhs):", lambda r: entry_widget(r, 5.0)),
        ("Kms Driven:",            lambda r: entry_widget(r, 30000)),
        ("Fuel Type:",             lambda r: combo_widget(r, ["Petrol","Diesel","CNG"], "Petrol")),
        ("Seller Type:",           lambda r: combo_widget(r, ["Dealer","Individual"], "Dealer")),
        ("Transmission:",          lambda r: combo_widget(r, ["Manual","Automatic"], "Manual")),
        ("Owner (0 – 3):",         lambda r: entry_widget(r, 0)),
    ]

    vars_ = []
    for i, (label_text, widget_fn) in enumerate(fields):
        make_label(i, label_text)
        vars_.append(widget_fn(i))

    # ── Result label ──────────────────────────────────────────────────────────
    result_var = tk.StringVar(value="")
    result_lbl = tk.Label(root, textvariable=result_var,
                          bg=BG, fg=ACCENT,
                          font=("Segoe UI", 13, "bold"), pady=4)
    result_lbl.pack()

    # ── Predict button ────────────────────────────────────────────────────────
    def on_predict():
        try:
            row = pd.DataFrame([[
                int(vars_[0].get()),
                float(vars_[1].get()),
                int(vars_[2].get()),
                vars_[3].get(),
                vars_[4].get(),
                vars_[5].get(),
                int(vars_[6].get()),
            ]], columns=['Year','Present_Price','Kms_Driven',
                         'Fuel_Type','Seller_Type','Transmission','Owner'])

            transformed = transformer.transform(row)
            price = lr.predict(transformed)[0]
            result_var.set(f"✅  Predicted Selling Price:  ₹ {price:.2f} Lakhs")
        except ValueError as ve:
            messagebox.showerror("Input Error", f"Please check your inputs.\n\n{ve}")
        except Exception as ex:
            messagebox.showerror("Error", str(ex))

    btn = tk.Button(root, text="  Predict Selling Price  ",
                    command=on_predict,
                    bg=ACCENT, fg=BTN_FG,
                    font=("Segoe UI", 11, "bold"),
                    relief="flat", cursor="hand2",
                    padx=12, pady=8,
                    activebackground="#6a5ce0", activeforeground=BTN_FG)
    btn.pack(pady=(0, 20))

    root.mainloop()

launch_ui()