# -*- coding: utf-8 -*-
"""Untitled15(1).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1I2rLn23GLHFDQoE1l3J8D0vc6h3sF_wV
"""

import os
from pathlib import Path
import shutil
import random
import torch
import torch.nn as nn
import torchinfo
from torchinfo import summary
from torchvision import datasets, models, transforms

import PIL
from PIL import Image

import torch.utils
import torch.optim as optim
from torch.utils.data import DataLoader, random_split

from collections import Counter
from tqdm.notebook import tqdm

import pandas as pd
import matplotlib.pyplot as plt

downloadedfile = Path(r"C:\Users\Jelil\Downloads\archive(4).zip")
base_dir = Path(r"C:\Users\Jelil\Desktop\New folder (7)")

import zipfile
with zipfile.ZipFile(downloadedfile, "r") as f:
    f.extractall(base_dir)

height = 224
width = 224

transform = transforms.Compose([
    transforms.Resize((height, width)),
    transforms.ToTensor()
    ])

dataset_path = r"C:\Users\Jelil\Desktop\New folder (7)\seg_train\seg_train"
datasetz = datasets.ImageFolder(root = dataset_path, transform = transform)

classes = {v:k for k,v in datasetz.class_to_idx.items()}
print(classes)

n_class = len(datasetz.class_to_idx)
print(n_class)

count = Counter([label for _,label in tqdm(datasetz,desc="counting", leave = False)])
print(count)

class_distribution = {classes[k]:v for k,v in count.items()}
print(class_distribution)

class_distribution = {classes[k]:v for k,v in count.items()}
print(class_distribution)

df_class_distribution = pd.Series(class_distribution)

# Make a bar chart from the function output
df_class_distribution.plot(kind = "bar")

# Add axis labels and title
plt.xlabel("Class Label")
plt.ylabel("Frequency [count]")
plt.title("Distribution of Classes in Training Dataset");

batch_size = 64
dataset_loader = DataLoader(datasetz, batch_size = batch_size, shuffle= True)

first_batch = next(iter(dataset_loader))
print(f"Shape of one batch: {first_batch[0].shape}")

def get_mean_std(loader):

    channels_sum, channels_squared_sum, num_batches = 0, 0, 0

    for data, _ in tqdm(loader):
        channels_sum += torch.mean(data, dim=[0, 2, 3])
        channels_squared_sum += torch.mean(data**2, dim=[0, 2, 3])
        num_batches += 1

        mean = channels_sum/num_batches

        std = (channels_squared_sum/num_batches - mean**2)**0.5
        return mean, std

mean, std = get_mean_std(dataset_loader)
print(f"Mean: {mean}")
print(f"Standard deviation: {std}")

height = 224
width = 224

transformNorm = transforms.Compose([
    transforms.Resize((height, width)),
    transforms.ToTensor(),
    transforms.Normalize(mean = mean, std= std)
    ])

train_transform = transforms.Compose([
    transforms.RandomResizedCrop(224),
    transforms.RandomHorizontalFlip(),
    transforms.RandomRotation(15),
    transforms.ColorJitter(0.2, 0.2, 0.2, 0.02),

    transforms.ToTensor(),
    transforms.RandomErasing(p=0.25),

    transforms.Normalize(
        mean=mean,
        std=std
    )
])

dataset = datasets.ImageFolder(root = dataset_path, transform = train_transform)

g = torch.Generator()
g.manual_seed(42)

train_dataset, val_dataset = random_split(dataset, [0.85, 0.15] , generator=g)

test_dataset_path = r"C:\Users\Jelil\Desktop\New folder (7)\seg_test\seg_test"
test_dataset = datasets.ImageFolder(root = test_dataset_path, transform = transformNorm )

train_loader = DataLoader(train_dataset, batch_size=64, shuffle=True)
val_loader = DataLoader(val_dataset, batch_size=64, shuffle=False)
TestLoader = DataLoader(test_dataset, batch_size=64, shuffle=False)

image , _ = next(iter(train_loader))
print(image.shape)

import torch
import torch.nn as nn

class CNN(nn.Module):
    def __init__(self):
        super().__init__()

        self.features = nn.Sequential(
            nn.Conv2d(3, 16, 3, padding=1),
            nn.ReLU(),
            nn.MaxPool2d(4),

            nn.Conv2d(16, 32, 3, padding=1),
            nn.ReLU(),
            nn.MaxPool2d(4),

            nn.Conv2d(32, 64, 3, padding=1),
            nn.ReLU(),
            nn.MaxPool2d(4),

            nn.Conv2d(64, 128, 3, padding=1),
            nn.ReLU(),
            nn.Dropout2d(0.3)
        )

        # ⭐ FIX 1: flat_size must be computed before using it
        with torch.no_grad():
            dummy = torch.randn(1, 3, 224, 224)
            out = self.features(dummy)
            flat_size = out.numel()

        self.classifier = nn.Sequential(
            nn.Flatten(),
            nn.Dropout(),
            nn.Linear(flat_size, 500),
            nn.ReLU(),
            nn.Dropout(),
            nn.Linear(500, n_class)
        )

    def forward(self, x):
        x = self.features(x)
        x = self.classifier(x)
        return x
modelnew = CNN()

loss_fn = nn.CrossEntropyLoss()
optimizer = torch.optim.Adam(modelnew.parameters(), lr = 0.001, weight_decay=0.0001)

from torch.optim.lr_scheduler import StepLR
step_size = 4
# Multiplicative factor of learning rate decay
gamma = 0.2
# Initialize the learning rate scheduler
scheduler = StepLR(
    optimizer,
    step_size=step_size,
    gamma=gamma,
    )

def checkpointing(validation_loss, best_val_loss, modelnew, optimizer, save_path):
    """Function that implements Checkpointing"""
    if validation_loss < best_val_loss:
        torch.save(
        {
        "modelnew_state_dict": modelnew.state_dict(),
        "optimizer_state_dict": optimizer.state_dict(),
        "loss": best_val_loss
        },
        save_path,
        )
    print(f"Checkpoint saved with validation loss {validation_loss:.4f}")

def early_stopping(validation_loss, best_val_loss, counter):
    """Function that implements Early Stopping"""
    stop = False
    if validation_loss < best_val_loss:
        counter = 0
    else:
        counter += 1
    if counter >= 5: # our patience is 5 epochs
        stop = True
    return counter, stop

def score(modelnew, data_loader, loss_fn, device="cpu"):
    total_loss = 0
    total_correct = 0
    modelnew.eval()
    with torch.no_grad():
        for inputs, targets in tqdm(data_loader, desc="Scoring", leave=False):
            inputs = inputs.to(device)
            output = modelnew(inputs)
            targets = targets.to(device)
            loss = loss_fn(output, targets)
            total_loss += loss.data.item() * inputs.size(0)
            correct = torch.eq(torch.argmax(output, dim=1), targets)
            total_correct += torch.sum(correct).item()
    n_observations = data_loader.batch_size * len(data_loader)
    average_loss = total_loss / n_observations
    accuracy = total_correct / n_observations
    return average_loss, accuracy

def train_epoch(modelnew, optimizer, loss_fn, data_loader, device="cpu"):
    training_loss = 0.0
    modelnew.train()

    for inputs, targets in tqdm(data_loader, desc="Training", leave=False):
        optimizer.zero_grad()
        inputs = inputs.to(device)
        targets = targets.to(device)
        output = modelnew(inputs)
        loss = loss_fn(output, targets)
        loss.backward()
        optimizer.step()
        training_loss += loss.data.item() * inputs.size(0)
    return training_loss / len(data_loader.dataset)

def train(
    modelnew,
    optimizer,
    loss_fn,
    train_loader,
    val_loader,
    epochs=20,
    device="cpu",
    scheduler=None,
    checkpoint_path=None,
    early_stopping=None,
):
    # Track metrics
    train_losses = []
    train_accuracies = []
    val_losses = []
    val_accuracies = []
    learning_rates = []

    best_val_loss = float("inf")
    early_stopping_counter = 0


    for epoch in range(1, epochs + 1):
        print("\n")
        print(f"Starting epoch {epoch}/{epochs}")

        # Train one epoch
        train_epoch(modelnew, optimizer, loss_fn, train_loader, device)

        # Evaluate training
        train_loss, train_accuracy = score(modelnew, train_loader, loss_fn, device)
        train_losses.append(train_loss)
        train_accuracies.append(train_accuracy)

        # Evaluate validation
        validation_loss, validation_accuracy = score(modelnew, val_loader, loss_fn, device)
        val_losses.append(validation_loss)
        val_accuracies.append(validation_accuracy)

        print(f"Epoch: {epoch}")
        print(f"Training loss: {train_loss:.4f}")
        print(f"Training accuracy: {train_accuracy*100:.4f}%")
        print(f"Validation loss: {validation_loss:.4f}")
        print(f"Validation accuracy: {validation_accuracy*100:.4f}%")

        # Log LR
        lr = optimizer.param_groups[0]["lr"]
        learning_rates.append(lr)

        if scheduler:
            scheduler.step()

        # Checkpointing
        if checkpoint_path:
            checkpointing(
                validation_loss, best_val_loss, modelnew, optimizer, checkpoint_path
            )

        # Early stopping
        if early_stopping:
            early_stopping_counter, stop = early_stopping(
                validation_loss, best_val_loss, early_stopping_counter
            )
            if stop:
                print(f"Early stopping triggered after {epoch} epochs")
                break

        # Update best loss
        if validation_loss < best_val_loss:
            best_val_loss = validation_loss

    return (
        learning_rates,
        train_losses,
        val_losses,
        train_accuracies,
        val_accuracies,
        epoch,
    )

device = "cuda" if torch.cuda.is_available() else "cpu"
modelnew.to(device)

epochs_to_train = 50

checkpoint_path = Path(
    r"C:\Users\Jelil\Desktop\New folder (7)\best_modelnew.pth"
)

train_results = train(
    modelnew,
    optimizer,
    loss_fn,
    train_loader,
    val_loader,
    epochs=epochs_to_train,
    device=device,
    scheduler=scheduler,
    checkpoint_path= checkpoint_path,
    early_stopping=early_stopping,
    )

checkpoint = torch.load(
    r"C:\Users\Jelil\Desktop\New folder (7)\best_modelnew.pth",
    map_location="cpu"
)

modelnew.load_state_dict(checkpoint["modelnew_state_dict"])

optimizer.load_state_dict(checkpoint["optimizer_state_dict"])

modelnew.eval()

modelnew.eval()
with torch.no_grad():
    all_probs = torch.tensor([])
    for images, labels in tqdm(TestLoader, desc = "Testing on unseen data", leave = False):
        pred = modelnew(images)
        pred_out1 = torch.nn.functional.softmax(pred, dim = 1)
        all_probs = torch.cat((all_probs, pred_out1),dim = 0)

predictions = torch.argmax(all_probs, dim = 1)

from sklearn.metrics import ConfusionMatrixDisplay, confusion_matrix
import matplotlib.pyplot as plt

targets_val = torch.cat([labels for _, labels in tqdm(TestLoader, desc="Get Labels", leave = False)])

cm = confusion_matrix(targets_val, predictions)
disp = ConfusionMatrixDisplay(confusion_matrix=cm, display_labels=classes.values())
# Set figure size

plt.figure(figsize=(10, 8))
disp.plot(cmap=plt.cm.Blues, xticks_rotation="vertical")

from sklearn.metrics import precision_score, recall_score

precision = precision_score(targets_val, predictions, average='macro')
recall = recall_score(targets_val, predictions, average='macro')

print("Precision:", precision)
print("Recall:", recall)

image.shape

image_path = r"C:\Users\Jelil\Desktop\New folder (7)\seg_test\seg_test\buildings\20057.jpg"
image = Image.open(image_path)
image

image = transformNorm(image)
image = image.unsqueeze(0)
modelnew.eval()
with torch.no_grad():
    pred = modelnew(image)
    pred_out1 = torch.nn.functional.softmax(pred, dim = 1)
    prediction = torch.argmax(pred_out1, dim = 1)
print(classes[prediction.item()])

